import type { Metadata } from "next";
import { Header } from "@/components/modules/Header";
import "../styles/global.scss";
import style from "./page.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.wrapper}>
          <Header />
          <main className={style.page}>{children}</main>
        </div>
      </body>
    </html>
  );
}
